name: Documentation

on:
  push

env:
  PRNO: ${{ github.event.pull_request.number }}

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        run: echo "====|$PRNO|===="
